parameters:

services:
  azine.socialBarHelper:
    class: Azine\SocialBarBundle\Templating\SocialBarHelper
    arguments: ["@twig"]
    public: true

  twig.extension.azine_social_bar:
    class: Azine\SocialBarBundle\Templating\SocialBarTwigExtension
    tags:
      - { name: 'twig.extension' }
    arguments: ["@azine.socialBarHelper"]
