parameters:

services:
  azine.socialBarHelper:
    class : Azine\SocialBarBundle\Templating\SocialBarHelper
    tags :
      - {name : 'templating.helper', alias : 'social-buttons'}
    arguments : [ @templating ]

  twig.extension.azine_social_bar:
    class: Azine\SocialBarBundle\Templating\SocialBarTwigExtension
    tags:
        - { name: 'twig.extension' }
    arguments : [ @service_container ]
