# default-configurations
imports:
    - javascript
    - php   
    
tools:
    external_code_coverage:
        timeout: 1200 # Timeout 20min in seconds.

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
