language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

before_script: 
    - composer update --dev --prefer-source
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
    - composer install

script: 
  - phpunit --coverage-text --coverage-clover=coverage.clover /home/travis/build/azine/AzineSocialBarBundle/Tests/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: travis@azine-it.ch



