language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=dev-master

before_script: 
  - ls -a /home/travis/build/azine/* -R
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --dev
  - composer -vvv install --dev --prefer-source

script: 
  - phpunit --coverage-text --coverage-clover=coverage.clover /home/travis/build/azine/AzineSocialBarBundle/Tests/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: travis@azine-it.ch

